In [1]:
#1 

In [2]:
#Arethmetic opperators

In [3]:
3+3

6

In [4]:
9-6

3

In [5]:
3*5

15

In [6]:
99/9

11.0

In [8]:
3**3

27

In [9]:
3 % 2

1

In [10]:
a=10 

In [11]:
b= 20

In [12]:
a==b

False

In [14]:
a!=b

True

In [15]:
a>b

False

In [16]:
a<b

True

In [17]:
a>=b

False

In [18]:
a<=b

True

In [19]:
a>10 and b<10

False

In [21]:
a<10 or b<10

True

In [22]:
not (a<10 or b<10)

False

In [23]:
# 2

In [1]:
colors = ['red', 'green', 'blue', 'yellow', 'white', 'black']


In [2]:
colors[2]

'blue'

In [3]:
colors[-2]

'white'

In [4]:
colors[1:3]

['green', 'blue']

In [5]:
#3

In [29]:
theSum = 0
num = 1
while num <= 100:
    x=num
    print (num)
    num = num + x

1
2
4
8
16
32
64


In [30]:
#4

In [33]:
import pandas as pd 

In [34]:
df1=pd.read_csv('D:\Python_Assignments\crime_data.csv')

In [36]:
df1.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [37]:
df = pd.DataFrame({'States':['Maharashtra', 'Kerala', 'Rajasthan', 'Uttarakhand', 'TN', 'Telangana'],
    'Capitals':['Mumbai', 'Thiruvananthapuram', 'Jaipur', 'Dehradun', 'Chennai', 'Hyderabad'],
    'Population':['95078529', '11293551', '323415', '6193968', '5253355', '2227032']})

In [38]:
df.to_excel('./states.xlsx')

In [39]:
#5

In [42]:
#6

In [43]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [44]:
#7

In [47]:
import numpy as np
l = [10.23,13.92,600,46.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [10.23, 13.92, 600, 46.32]
One-dimensional NumPy array:  [ 10.23  13.92 600.    46.32]


In [48]:
#8

In [50]:
import numpy as np
a = np.zeros(10)
print(a)
print("Update sixth value to 11")
a[6] = 11
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
